platform :ios, '14.0'

# Frameworks 설정
linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# React Native 프로젝트 준비
# React Native의 최신 버전에서는 prepare_react_native_project!를 사용하는 대신, `use_react_native!` 메소드에서 직접 설정을 수행합니다.

target 'tourmate_frontend' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Google Maps SDK 설정
  pod 'GoogleMaps', '~> 6.0.0'
  pod 'Google-Maps-iOS-Utils', '~> 3.10.0'

  target 'tourmate_frontendTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # React Native 포스트 설치 스크립트
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
